apiVersion: v1
kind: Secret
metadata:
  name: {{ postgres_secrets.name }}
type: {{ postgres_secrets.type }}
data:
{% if postgres_user is defined %}
  "postgres-user": "{{ postgres_user|default('postgres') | b64encode }}"
{% endif %}
{% if postgres_password is defined %}
  "postgres-password": "{{ postgres_password | b64encode }}"
{% endif %}
{% if replication.user is defined %}
  "repl-user": "{{ replication.user | default('replicator') | b64encode }}"
{% endif %}
{% if replication.password is defined %}
  "repl-password": "{{ replication.password | b64encode }}"
{% endif %}
